COCO_PT = {
    "person": "pessoa",
    "bicycle": "bicicleta",
    "car": "carro",
    "motorcycle": "moto",
    "airplane": "aviao",
    "bus": "onibus",
    "train": "trem",
    "truck": "caminhao",
    "boat": "barco",
    "traffic light": "semaforo",
    "fire hydrant": "hidrante",
    "stop sign": "placa de pare",
    "parking meter": "parquimetro",
    "bench": "banco",
    "bird": "passaro",
    "cat": "gato",
    "dog": "cachorro",
    "horse": "cavalo",
    "sheep": "ovelha",
    "cow": "vaca",
    "elephant": "elefante",
    "bear": "urso",
    "zebra": "zebra",
    "giraffe": "girafa",
    "backpack": "mochila",
    "umbrella": "guarda-chuva",
    "handbag": "bolsa",
    "tie": "gravata",
    "suitcase": "mala",
    "frisbee": "frisbee",
    "skis": "esqui",
    "snowboard": "snowboard",
    "sports ball": "bola",
    "kite": "pipa",
    "baseball bat": "taco",
    "baseball glove": "luva",
    "skateboard": "skate",
    "surfboard": "prancha",
    "tennis racket": "raquete",
    "bottle": "garrafa",
    "wine glass": "taca",
    "cup": "copo",
    "fork": "garfo",
    "knife": "faca",
    "spoon": "colher",
    "bowl": "tigela",
    "banana": "banana",
    "apple": "maca",
    "sandwich": "sanduiche",
    "orange": "laranja",
    "broccoli": "brocolis",
    "carrot": "cenoura",
    "hot dog": "cachorro-quente",
    "pizza": "pizza",
    "donut": "rosquinha",
    "cake": "bolo",
    "chair": "cadeira",
    "couch": "sofa",
    "potted plant": "planta",
    "bed": "cama",
    "dining table": "mesa",
    "toilet": "vaso sanitario",
    "tv": "tv",
    "laptop": "laptop",
    "mouse": "mouse",
    "remote": "controle",
    "keyboard": "teclado",
    "cell phone": "celular",
    "microwave": "microondas",
    "oven": "forno",
    "toaster": "torradeira",
    "sink": "pia",
    "refrigerator": "geladeira",
    "book": "livro",
    "clock": "relogio",
    "vase": "vaso",
    "scissors": "tesoura",
    "teddy bear": "urso de pelucia",
    "hair drier": "secador",
    "toothbrush": "escova de dente",
}
